# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"

# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

MANDRILL_APIKEY: O-2Ch-EYlDtLZ3CEqem0Cg